name: Fuck U Code Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:


jobs:
  scan-code:
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
        case_type: 
          - python
        case_id: 
          - 1
        reverse_score:
          - 'true'
          - 'false'

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: init submodules
        run: |
          git submodule update --init --recursive

      - name: Scaning
        uses: ./
        with:
          target-path: tests/${{matrix.case_type}}/case_${{matrix.case_id}} # scan src package only
          reverse-score: ${{matrix.reverse_score}}
          badge-text: ${{matrix.case_type}}_case_%23${{matrix.case_id}}
          badge-file-name: fuck-u-code_scan
          badge-logo-id: ${{matrix.case_type}}
          badge-artifact-name: upload-my-awesome-badge-${{ github.run_id }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          R2_BUCKET: ${{ secrets.R2_BUCKET }}
          R2_badge_path: badge_dir_with_uniq_name/FUC-GHA/tests/${{matrix.case_type}}_case_#${{matrix.case_id}}_${{matrix.reverse_score}}
